[dependencies]
wasm-bindgen = "0.2"
scheduler_core = {path = "../scheduler_core"}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0.140"

[lib]
crate-type = ["cdylib"]

[package]
name = "scheduler_wasm"
version = "0.1.0"
edition = "2021"
