[dependencies]
wasm-bindgen = "0.2"
scheduler_core = { path = "../scheduler_core" }
serde = { version = "1.0", features = ["derive"] }

[package]
name = "generate_schedule_milp_wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
